### ISSUE TITLE
In Custom Cinnamon Menu, if the list of applications is too long, the context menu doesn't show up

### ISSUE THREAD

**Issue by pizzadude** [Odyseus/CinnamonTools#20] opened 2017-01-25 11:44 UTC
In Custom Cinnamon Menu, If the list of applications is too long (for example, there's a scrollbar) and you right click, the context menu doesn't show up, or is too short.

**Comment by Odyseus** [comment] 2017-01-26 12:33
Hello, @pizzadude.

I can't reproduce this issue you describe in any Cinnamon version supported by Custom Cinnamon Menu applet.

Under normal circumstances, when you right click an application to open its context menu, the context menu should open. If the context menu would not "fit", the applications list should automatically scroll to make all items on the context menu visible. I have seen the behavior that you describe several times using not only my menu, but also in the default Cinnamon menu and other forks. But I could never find the culprit of such issue nor what triggered it. And after a Cinnamon restart all would come back to normal.

I will need more details from you. The output of the `inxi -S` command (some basic system info) and the content of the **~/.cinnamon/glass.log** and **~/.xsession-errors** (some log files) would be a start. By running the following three commands you will get a URL for each of them that you can then post in here.

```
inxi -S | pastebin
```

```
pastebin ~/.cinnamon/glass.log
```

```
pastebin ~/.xsession-errors
```

**Comment by pizzadude** [comment] 2017-01-26 19:30
.xsession-errors contains sensitive information, so I won't share it.

glass.log : https://gist.github.com/9f4efeef4032c746c6142e9bf3cd6cc1

inxi : https://gist.github.com/29798e88db63d38ad92ed8179fb3c13d

**Comment by Odyseus** [comment] 2017-01-26 21:08
Well, sadly, the **.xsession-errors** file was the one that could actually contain an error/warning message. Either way, I wasn't hopeful to see any error in any of the logs.

I'm gonna close this issue for the moment. If you come up with precise reproducible steps to replicate the issue in this applet or any other applet based on the original menu, feel free to report it here.

**Comment by Odyseus** [comment] 2017-01-26 21:10
@pizzadude.

The Custom Cinnamon Menu applet has a lot of settings (it's very convoluted really). It occurred to me that maybe a combination of certain settings might be causing your issue. You could export your current settings for the applet and then upload it into a GitHub Gist (you can delete it afterwards). You can edit it with any text editor to remove any sensible data (like full paths, etc.). Using your settings file, I might be able to replicate your issue and with any luck fix it.

**Comment by pizzadude** [comment] 2017-01-26 22:49
@Odyseus 

I uploaded the settings file (.json)

https://gist.github.com/anonymous/e5f93201734a00f529ff62cc16072c0d

**Comment by pizzadude** [comment] 2017-01-26 22:51
Note: The context menu opens if there is no long scrollbar. If there is a long scrollbar, the context menu doesn't open.

**Comment by Odyseus** [comment] 2017-01-28 00:16
@pizzadude.

I tested the Custom Cinnamon Menu applet with your settings and I cannot reproduce the issue that you are experiencing. Neither on Cinnamon 3.0.7 nor on Cinnamon 3.2.7.

The only thing that I can think of is a theme issue. I only use themes based on Mint-X, and I don't see any problems with those themes.

Sorry that I couldn't be of more help to you.

**Closed by Odyseus** 2017-01-28 00:16 UTC

**Comment by pizzadude** [comment] 2017-01-28 01:56
@Odyseus  I use Mint-Y Dark. I tried Mint-X and the issue went away. I think the issue is with Mint-Y Dark (or Mint-Y)
