### ISSUE TITLE
Cinnamon tweaks > Window Tweaks > Decoration Removal

### ISSUE THREAD

**Issue by JonathanGallagher** [Odyseus/CinnamonTools#55] opened 2017-05-06 03:37 UTC
### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
Open a program
2. [Second Step]
Maximize

**Expected behavior:** [What you expect to happen]
A window to maximize and remove borders, and unmaximize and regain borders.

**Actual behavior:** [What actually happens]
For some programs (file manager and other cinnamon specific programs like settings manager, and also terminal) the extension works as expected.  However for most programs it does not.

On firefox, if window is in maximized state, and closed, when reopened, it is maximized, and visible.  When unmaximized the decorations remain unpresent.  If started in unmaximized state, program window disappears.

For most other programs:  thunderbird, mousepad, atom text editor, and others, if opened in maximized state, the window is invisible.  If opened in minimized state and then maximized the window becomes invisible.  Close and reopen does not help.  

Also, the "edit applications list" is grayed out and can't be edited.  Have selected use applications list as blacklist, but as far as I know this list is empty (at least, I have never edited).

Running arch linux.  xprop and xwininfo are installed.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Every time.

I will help, however I can.

### System information

inxi -xxxSc0 -! 31

### System logs

pastebin ~/.cinnamon/glass.log
pastebin ~/.xsession-errors:

Here is link to xsession-errors:
http://dpaste.com/2XJHQ70

glass.log is empty (doesn't exist).

**Comment by Odyseus** [comment] 2017-05-06 06:27
Hello, @JonathanGallagher.

Thanks for your detailed bug report. Lets start with the easy part.

> Also, the "edit applications list" is grayed out and can't be edited. Have selected use applications list as blacklist, but as far as I know this list is empty (at least, I have never edited).

This is a bug in **Cinnamon Tweaks** settings window. I assigned the wrong dependency key to that specific button. It is already fixed on the version found on this repository. You can temporarily fix it by enabling the tweak called **Auto move windows**.

I cannot reproduce the issue that you describe (invisible windows) on my Archlinux system (a virtual machine). Although, I do note a *flash* when maximizing a window, like it gets invisible for a split second and then reappears with the title bar gone (I'm starting to think that the video driver might have something to do in all this). I don't know if this will help but, when you have an invisible window, do not close it when it is invisible, unmaximize it, then close it and then reopen it and maximize it again.

Sadly, these are all known issues that may never be fixed, since Cinnamon doesn't have a native way of hiding its window decorations. This tweak is very *hacky* to say the least and we are very lucky that it works (or half-works) as it is.

You will have to re-evaluate if you want to use this tweak and learn to live with its issues. If what you want is to remove the decorations of absolutely all maximized windows without exceptions, then you are better off applying a tweak to the window decorations theme that you use (I will add a *how-to* to the help file to explain how to achieve this). It works perfectly and without any of the issues that the tweak in this extension has. At the end of this message I will attach the instructions just in case that you want to try it.

Your **.xsession-errors** file doesn't show any error related this extension nor any other Cinnamon xlet.

> glass.log is empty (doesn't exist).

You might want to enable this log in case of future problems with any Cinnamon xlet. **System Settings** > **General** > **Log LookingGlass output to ~/.cinnamon/glass.log**

## Alternative
There is an alternative way of hiding the title bar of absolutely all maximized windows without exceptions. By editing your Metacity theme (window decorations theme). It works infinitely better and without any of the issues this tweak on this extension has.

- Simply go to `/Path/To/Your/Theme/metacity-1` folder and edit with any text editor the file called **metacity-theme-3.xml**. If that file doesn't exists in your theme, then it should exist one called **metacity-theme-2.xml** or **metacity-theme-1.xml**. Choose the one with the bigger number.
- Find the **frame_geometry** element named **max** (or **maximized** or **normal_max** or **normal_maximized**). Its exact name may vary depending on the theme.
- Basically, one has to set to that element the attribute **has_title** to false, and then set all sizes of all its properties to 0 (zero). Some themes might require to add more properties and set them to 0 (zero) to completely get rid of the title bar.
- Next you will find examples on how to edit the Metacity themes found on the **Mint-X** and **Mint-Y** themes.

##### For the Metacity theme found on the Mint-X theme
```xml
<frame_geometry name="maximized" has_title="false" title_scale="medium" parent="normal" rounded_top_left="false" rounded_top_right="false">
    <distance name="right_width" value="0" />
    <distance name="left_titlebar_edge" value="0"/>
    <distance name="right_titlebar_edge" value="0"/>
    <distance name="title_vertical_pad" value="0"/>
    <border name="title_border" left="0" right="0" top="0" bottom="0"/>
    <border name="button_border" left="0" right="0" top="0" bottom="0"/>
    <distance name="bottom_height" value="0" />
</frame_geometry>
```

##### For the Metacity theme found on Mint-Y theme
```xml
<frame_geometry name="max" has_title="false" title_scale="medium" parent="normal" rounded_top_left="false" rounded_top_right="false">
    <distance name="right_width" value="0" />
    <distance name="left_titlebar_edge" value="0"/>
    <distance name="right_titlebar_edge" value="0"/>
    <distance name="title_vertical_pad" value="0"/>
    <border name="title_border" left="0" right="0" top="0" bottom="0"/>
    <border name="button_border" left="0" right="0" top="0" bottom="0"/>
    <distance name="bottom_height" value="0" />
    <distance name="button_width" value="0"/>
    <distance name="button_height" value="0"/>
</frame_geometry>
```

**Comment by JonathanGallagher** [comment] 2017-05-06 07:35
Okay great!  Thanks for the information.

**Closed** 2017-05-10 20:10 UTC
Labels: bug, cantfix, Cinnamon Tweaks

**Comment by Odyseus** [comment] 2017-06-13 03:46
Hello, @JonathanGallagher.

I tracked down the problem of invisible windows and fixed it (at least, I cannot reproduce it anymore on Cinnamon 3.4.x). If you are still using the extension, with the next update (I published it just now and awaiting review) there will be a new option called **Enable hack for invisible windows**. After enabling this option, all windows with decorations removed needs to be restarted. Read the option tooltip for know *side effects*.
