### ISSUE TITLE
Simple ToDo List applet - Localisation issue

### ISSUE THREAD

**Issue by eson57** [Odyseus/CinnamonTools#86] opened 2017-05-20 14:15 UTC
Hi,
I'm working on Swedish translation for Simple ToDo List and ran into some error.

### Description
Translated tag names and other strings don't translate in example tasks list. Error shown in screen shot below. Translated tag names works fine in user created tasks list, also seen below.

![2017-05-20_15-52-09](https://cloud.githubusercontent.com/assets/2996154/26276360/53f60bfe-3d76-11e7-9cbe-8f6f58a00e1b.png)
![2017-05-20_15-50-51](https://cloud.githubusercontent.com/assets/2996154/26276366/68053cb4-3d76-11e7-86e2-6ce5ee56c3dc.png)

### System information
Kernel: 4.4.0-78-generic x86_64 (64 bit gcc: 5.4.0)
Desktop: Cinnamon 3.2.7 (Gtk 3.18.9) dm: mdm Distro: Linux Mint 18.1 Serena

### Edit:
I can see now that it works fine after resetting the example tasks list. So I guess this is not an issue after all, is it?

**Comment by Odyseus** [comment] 2017-05-20 20:26
Hello, @eson57.

I couldn't reproduce your issue. I tested it with a fully translated applet and all the examples were also translated.

What I thing that could have happened is (and this is a total guess) that you placed an instance of this applet in a panel with your translations not completed yet. The examples are created and translated *on-the-fly*. If some words or phrases aren't translated, they are saved as they are. Even if later you restart Cinnamon with a fully translated applet, the untranslated strings on the examples will continue to be untranslated.

I will close this issue, but you can keep reporting here if you find more problems and/or a precise ways to reproduce them.

**Closed by Odyseus** 2017-05-20 20:26 UTC

**Comment by eson57** [comment] 2017-05-21 03:38
Yes, your guess is exactly what happened, so case closed. Thanks for the explanation. I'll push the translation when finished.
